# Generated by Django 3.0 on 2019-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAInference', '0005_auto_20191210_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysisinference',
            name='result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentanalysisinference',
            name='text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
